package org.windbell.lab.hamster.validate.value;

public class Value {
	public static String SINGEL = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
			+ "<request>"
			+ "<amount>4234.90</amount>"
			+ "<bizNo>DD-ZJHB2015072700000008</bizNo>"
			+ "<bizType>04</bizType>"
			+ "<cdtrAcctName>Company</cdtrAcctName>"
			+ "<cdtrAcctNo>591902896010305</cdtrAcctNo>"
			+ "<cdtrAcctType>O</cdtrAcctType>"
			+ "<cdtrBankAddr>招商银行福州分行地址</cdtrBankAddr>"
			+ "<cdtrBankCode>308391026010</cdtrBankCode>"
			+ "<cdtrBankId>CMB</cdtrBankId>"
			+ "<cdtrBankName>福州分行</cdtrBankName>"
			+ "<cdtrCity>福州市</cdtrCity>"
			+ "<cdtrProv>福建省</cdtrProv>"
			+ "<chanId>04</chanId>"
			+ "<currency>CNY</currency>"
			+ "<dbtrAcctName>Company</dbtrAcctName>"
			+ "<dbtrAcctNo>591902896010504</dbtrAcctNo>"
			+ "<dbtrAcctType>O</dbtrAcctType>"
			+ "<dbtrBankAddr>招商银行福州分行地址</dbtrBankAddr>"
			+ "<dbtrBankCode>308391026010</dbtrBankCode>"
			+ "<dbtrBankId>CMB</dbtrBankId>"
			+ "<dbtrBankName>福州分行</dbtrBankName>"
			+ "<dbtrCity>福州市</dbtrCity>"
			+ "<interBankFlag>1</interBankFlag>"
			+ "<localCityFlag>1</localCityFlag>"
			+ "<merchId>896010504</merchId>"
			+ "<payType>03</payType>"
			+ "<priority>Y</priority>"
			+ "<purpose>划拨</purpose>"
			+ "<serviceId>SP0001</serviceId>"
			+ "<tradeDate>20150727</tradeDate>"
			+ "<tradeTime>014643</tradeTime>"
			+ "<txnType>4</txnType>"
			+ "</request>";
	public static String BATCH = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
			+ "<request>"
			+ "<batchNo>PC-QYBX2015072300000006</batchNo>"
			+ "<bizType>03</bizType>"
			+ "<chanId>03</chanId>"
			+ "<currency>CNY</currency>"
			+ "<dbtrAcctName>中行企业</dbtrAcctName>"
			+ "<dbtrAcctNo>341556083131</dbtrAcctNo>"
			+ "<dbtrAcctType>O</dbtrAcctType>"
			+ "<dbtrBankAddr>陆家嘴西路168号正大广场B1F07-08单元 </dbtrBankAddr>"
			+ "<dbtrBankCode>104290006082</dbtrBankCode>"
			+ "<dbtrBankName>中国银行</dbtrBankName>"
			+ "<dbtrCity>北京市</dbtrCity>"
			+ "<dbtrbankId>BOC</dbtrbankId>"
			+ "<merchId>60830400</merchId>"
			+ "<payType>03</payType>"
			+ "<priority>N</priority>"
			+ "<record>"
			+ "<amount>20.22</amount>"
			+ "<bizNo>DD-QYBX2015072300000004</bizNo>"
			+ "<cdtrAcctName>SHENFA014061780</cdtrAcctName>"
			+ "<cdtrAcctNo>6012100025723</cdtrAcctNo>"
			+ "<cdtrAcctType>P</cdtrAcctType>"
			+ "<cdtrBankName>平安银行</cdtrBankName>"
			+ "<cdtrCity/>"
			+ "<cdtrProv/>"
			+ "<currency>CNY</currency>"
			+ "<interBankFlag>0</interBankFlag>"
			+ "<localCityFlag>0</localCityFlag>"
			+ "<txnType>P</txnType>"
			+ "</record>"
			+ "<record>"
			+ "<amount>10.68</amount>"
			+ "<bizNo>DD-QYBX2015072300000005</bizNo>"
			+ "<cdtrAcctName>SHENFA014061780</cdtrAcctName>"
			+ "<cdtrAcctNo>6012100025723</cdtrAcctNo>"
			+ "<cdtrAcctType>P</cdtrAcctType>"
			+ "<cdtrBankName>平安银行</cdtrBankName>"
			+ "<cdtrCity/>"
			+ "<cdtrProv/>"
			+ "<currency>CNY</currency>"
			+ "<interBankFlag>0</interBankFlag>"
			+ "<localCityFlag>0</localCityFlag>"
			+ "<txnType>P</txnType>"
			+ "</record>"
			+ "<serviceId>BP0002</serviceId>"
			+ "<totalAmount>30.90</totalAmount>"
			+ "<totalNum>2</totalNum>"
			+ "<tradeDate>20150726</tradeDate>"
			+ "<tradeTime>145330</tradeTime>" + "</request>";
	public static String SPEC_BATCH = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<request>"
			+ "<bizType>03</bizType>"
			+ "<serviceId>BP0002</serviceId>"
			+ "<batchNo>CMB_BX_CPC_00001</batchNo>"
			+ "<chanId>03</chanId>"
			+ "<totalNum>500</totalNum>"
			+ "<totalAmount>5.00</totalAmount>"
			+ "<tradeDate>20150725</tradeDate>"
			+ "<merchId>896010504</merchId>"
			+ "<dbtrBankName>招商银行</dbtrBankName>"
			+ "<dbtrBankId>CMB</dbtrBankId>"
			+ "<dbtrBankCode>59</dbtrBankCode>"
			+ "<dbtrAcctNo>591902896010504</dbtrAcctNo>"
			+ "<dbtrAcctName>福州分行</dbtrAcctName>"
			+ "<dbtrAcctType>O</dbtrAcctType>"
			+ "<dbtrCity>福州</dbtrCity>"
			+ "<payType>1</payType>"
			+ "<currency>CNY</currency>"
			+ "<record>"
			+ "<interBankFlag>1</interBankFlag>"
			+ "<bizNo>CMB_BX_CPC_00001_1</bizNo>"
			+ "<amount>0.01</amount>"
			+ "<currency>CNY</currency>"
			+ "<cdtrBankName>招商银行</cdtrBankName>"
			+ "<cdtrBankCode>59</cdtrBankCode>"
			+ "<cdtrBankId>59</cdtrBankId>"
			+ "<cdtrAcctNo>6225885910000108</cdtrAcctNo>"
			+ "<cdtrAcctName>Judy Zeng</cdtrAcctName>"
			+ "<cdtrAcctType>P</cdtrAcctType>"
			+ "<localCityFlag>0</localCityFlag>"
			+ "<cdtrProv>福州</cdtrProv>"
			+ "<cdtrCity>福州</cdtrCity>" 
			+ "</record>";
}
